# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "fruity"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marc-Andre Lafortune"]
  s.date = "2012-02-08"
  s.description = "Comparing apples with apples"
  s.email = "github@marc-andre.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".irbrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/fruity.rb",
    "lib/fruity/base.rb",
    "lib/fruity/baseline.rb",
    "lib/fruity/comparison_run.rb",
    "lib/fruity/group.rb",
    "lib/fruity/named_block_collector.rb",
    "lib/fruity/runner.rb",
    "lib/fruity/util.rb",
    "spec/baseline_spec.rb",
    "spec/comparison_run_spec.rb",
    "spec/find_thresold.rb",
    "spec/fruity_spec.rb",
    "spec/group_spec.rb",
    "spec/manual_test.rb",
    "spec/runner_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "spec/util_spec.rb"
  ]
  s.homepage = "http://github.com/marcandre/fruity"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Cool performance comparison tool"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

